runtime: java
env: flex
# runtime_config:
#   jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored

# env_variables : 
#   SPRING_DATA_MONGODB_URI: mongodb://cluster0-shard-00-00-u0m0f.gcp.mongodb.net:27017,cluster0-shard-00-02-u0m0f.gcp.mongodb.net:27017,cluster0-shard-00-01-u0m0f.gcp.mongodb.net:27017/custdb?replicaSet=rs0

# manual_scaling: 
#   instances: 1

# readiness_check:
#   path: "/readiness_check"
#   check_interval_sec: 5
#   timeout_sec: 4
#   failure_threshold: 2
#   success_threshold: 2
#   app_start_timeout_sec: 30000

# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10
  
# vm_health_check:
#   enable_health_check: False  
# health_check:
#   enable_health_check: False

#  SPRING_DATA_MONGODB_URI: mongodb://10.164.0.2:27017,10.164.0.3:27017/custdb?replicaSet=rs0
# cluster0-shard-00-00-u0m0f.gcp.mongodb.net:27017,cluster0-shard-00-02-u0m0f.gcp.mongodb.net:27017,cluster0-shard-00-01-u0m0f.gcp.mongodb.net:27017
